# Site settings
title: Software Design - Spring 2015
description: >
  Software Design | Spring 2015 | The Blake School | Minneapolis, MN
url: "http://blakecs-spring2015.github.io/"
email: shickey@blakeschool.org
github_username: blakecs-spring2015

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['scripts']
